[package]
name = "crayfish-context-macro"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
crayfish-syn.workspace = true
syn.workspace = true
quote.workspace = true
