[package]
name = "crayfish-space"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
crayfish-program.workspace = true
crayfish-space-macro.workspace = true
